### ISSUE TITLE
Open file failed

### ISSUE THREAD

**Issue by daxisunder** [redpenguinyt/display3d#2]

**Comment by redpenguinyt** [comment]
can you please provide more information? what file format were you importing? which version of display3d do you have? (you can check the installed version by running `display3d --version`)

if possible, please upload the file you are trying to display

**Comment by daxisunder** [comment]
Sorry, closed by accident. So, it outputs what I said earlier when testing the demo file. Installed with cargo, then compiled from source, the same issue. Now it's this weird bug.
![Screenshot_2024-02-18-15-52-04_11090](https://github.com/redpenguinyt/display3d/assets/148813505/6349457f-f400-4a4e-8908-6f7a903c7507)

**Comment by daxisunder** [comment]
I tried reinstalling rust and cargo, compiling again and rebooting, the same thing happens.
![Screenshot_2024-02-18-16-02-25_26953](https://github.com/redpenguinyt/display3d/assets/148813505/20755d8b-d831-4b90-ba20-71f743482be1)

**Comment by renpenguin** [comment]
it looks like your terminal's executing `cd -- display3d blahaj.obj -t 0,0,5.5`. This would attempt to cd into a folder named display3d with a bunch of additional arguments, which cd isnt liking. You'll need to run display3d without the `cd --` part

Also make sure that `blahaj.obj` is pointing to the actual blahaj's file path (in your case it'll be `/home/daxis/display3d/resources/blahaj.obj` if you've cloned the entire repo)

**Comment by daxisunder** [comment]
> it looks like your terminal's executing `cd -- display3d blahaj.obj -t 0,0,5.5`. This would attempt to cd into a folder named display3d with a bunch of additional arguments, which cd isnt liking. You'll need to run display3d without the `cd --` part

I understand what it's doing, I don't understand WHY it's doing that. As you can see in the screenshot, I didn't run cd, only the commands copied from your instructions. I tried deleting everything and compiling again, it's doing the same thing. Also, none of the other programs is doing that.

> Also make sure that `blahaj.obj` is pointing to the actual blahaj's file path (in your case it'll be `/home/daxis/display3d/resources/blahaj.obj` if you've cloned the entire repo)

I cloned the entire repo and checked multiple times, everything is where it should be.

**Comment by renpenguin** [comment]
do you have any aliases that could be messing with the command actually being sent to the shell?

**Comment by daxisunder** [comment]
I'm using Zoxide but other than that, no.

**Comment by renpenguin** [comment]
have you tried running the command with Zoxide disabled/uninstalled?
