### ISSUE TITLE
use github releases (or git tags at least)

### ISSUE THREAD

**Issue by koibtw** [redpenguinyt/display3d#4]
hey. i'd love to package this project. i could source from crates.io releases but IMO, getting the "source" straight from the "source" is better. so if you could just create github releases or git tags i'd be glad.

**Comment by renpenguin** [comment]
thank you for offering to do this! a tag has been created for the latest release `v0.1.17`. which platform(s) are you looking to package for?

**Comment by koibtw** [comment]
> which platform(s) are you looking to package for?

the AUR (will probably get transferred to arch extra but thats a WIP)
https://aur.archlinux.org/packages/display3d

having tags is a good practice for packaging overall. 
as well as having a license, afaik this project's code is in public domain unless a license is specified.
